export const NEWS_SERVICE_PENDING = 'news_service_pending'
export const NEWS_SERVICE_ERROR = 'news_service_error'
export const NEWS_SERVICE_SUCCESS = 'news_service_success'
export const NEWS_SEARCH_SERVICE_PENDING = 'news_search_service_pending'
export const NEWS_SEARCH_SERVICE_ERROR = 'news_search_service_error'
export const NEWS_SEARCH_SERVICE_SUCCESS = 'news_search_service_success'